magrittr_1 <- function() {
 5 %>%
   sin(.)
}



DotArrow_1 <- function() {
 5 %.>%
   sin(.)
}



BizarroPipe_1 <- function() {
 5 ->.;
   sin(.)
}



magrittr_2 <- function() {
 5 %>%
   sin(.) %>%
   sin(.)
}



DotArrow_2 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_2 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_5 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_5 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_5 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_10 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_10 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_10 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_15 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_15 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_15 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_20 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_20 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_20 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_25 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_25 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_25 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_50 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_50 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_50 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_100 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_100 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_100 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_200 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_200 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_200 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_500 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_500 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_500 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}



magrittr_1000 <- function() {
 5 %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.) %>%
   sin(.)
}



DotArrow_1000 <- function() {
 5 %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.) %.>%
   sin(.)
}



BizarroPipe_1000 <- function() {
 5 ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.) ->.;
   sin(.)
}


